// Code generated by Slice Machine. DO NOT EDIT.

import Embed from './Embed';
import EventInfo from './EventInfo';
import Image from './Image';
import LogoAnimation from './LogoAnimation';
import TextBlock from './TextBlock';

export {
	Embed,
	EventInfo,
	Image,
	LogoAnimation,
	TextBlock,
};

export const components = {
	embed: Embed,
	event_info: EventInfo,
	image: Image,
	logo_animation: LogoAnimation,
	text_block: TextBlock,
};
