// Code generated by Slice Machine. DO NOT EDIT.

import Embed from './Embed';
import EventInfo from './EventInfo';
import TextBlock from './TextBlock';

export {
	Embed,
	EventInfo,
	TextBlock,
};

export const components = {
	embed: Embed,
	event_info: EventInfo,
	text_block: TextBlock,
};
